### ISSUE TITLE
inf values in exported raster maps

### ISSUE THREAD

**Issue by petrasovaa** [f-tonini/SOD-modeling#12]
I suspect this line:

I_rast[] <- ifelse(I_rast[] == 0, NA, round(I_rast[]/Nmax_rast[], 1))

to cause zero division so in the output raster I have values inf which GRASS can't deal very well with. I tried this:
I_rast[] <- ifelse(I_rast[] == 0, NA, round(I_rast[]/Nmax_rast[Nmax_rast!= 0], 1))
but it gave me values over 1 which is wrong.

I uploaded changed host index with which I have trouble on velocity, it can be loaded in GRASS with r.unpack.

**Comment by f-tonini** [comment]
I tested it and do not get any errors with the current version on branch>>master...

**Comment by petrasovaa** [comment]
This is caused when creating the changed host index, the value of the host index must not be changed where there already is initial infection.
