### ISSUE TITLE
ncdf package not available any more

### ISSUE THREAD

**Issue by petrasovaa** [f-tonini/SOD-modeling#14]
it seems ncdf pacakge is no longer available:
https://cran.r-project.org/web/packages/ncdf/index.html

I am trying to use ncdf4 package but these changes are necssary:

```
mcf.array <- ncvar_get(nc_open('./layers/weather/weatherCoeff_2000_2014.nc'),  varid = "Mcoef") #M = moisture;
ccf.array <- ncvar_get(nc_open('./layers/weather/weatherCoeff_2000_2014.nc'),  varid = "Ccoef") #C = temperature;`
```

**Comment by f-tonini** [comment]
Thanks for spotting this. Fixed and updated in both master and develop branches.
